import { NextPage } from "next"
import Head from "next/head"
import Image from "next/image"
import { useContext, useState } from "react";
import Sidebar from "../src/components/Sidebar/Sidebar";
import FeedBacks from "../src/components/FeedBacks";

export default function Feedbacks() {
  const [isOpen, setIsOpen] = useState(false);

  const toggle = () => {
    setIsOpen((prev) => !prev);
  };

  return (
    <>
      <Head>
        <title>Tasking - Admin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Sidebar/>
      <FeedBacks/>
    </>
  )
}